kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: batchjob
  image: image
  command: >
    bash test_pvc.sh

  tensorboard:
    enabled: true

  storage:
    attachExistingPVCs:
      - name: testprojpvc-af7b62643072486e-test-0fae16c22bfc4f47
        mountPoint: /mnt/testprojpvc-af7b62643072486e-test-0fae16c22bfc4f47

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

